### ISSUE TITLE
Region bug not load 3.1.2 - 3.1.3

### ISSUE THREAD

**Issue by chocolatecraft** [Epicnicity322/PlayMoreSounds#2]
After 3.1.1 version region data not load.

**Comment by chrisrnj** [comment]
Hello, can you elaborate more? Do region sounds not play at all or you get an error? Have you tried deleting old regions from old version and creating new ones?

**Comment by chocolatecraft** [comment]
I set location and create region name. And then I run command /pms rg list its show region name until I reload plugin or restart server. Region location wont load (data save in Data folder but wont load) /pms rg list (plugin said no region location)

**Comment by chocolatecraft** [comment]
Whatever. I update from 3.1.1 I dont remove old data and create new. I am not sure it work or not.

**Comment by chrisrnj** [comment]
Thank you for reporting, I'll fix it in the next version.

**Comment by chocolatecraft** [comment]
I have another problem. When I leave from region. Leave fuction not run. I am not sure this fix on 3.1.2 or 3.1.3 already?

**Comment by chrisrnj** [comment]
That's a bug too, thank you again for reporting.

**Comment by chrisrnj** [comment]
Fixed both issues on latest version.
